// Generated by gencpp from file caster_app/DockGoal.msg
// DO NOT EDIT!


#ifndef CASTER_APP_MESSAGE_DOCKGOAL_H
#define CASTER_APP_MESSAGE_DOCKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caster_app
{
template <class ContainerAllocator>
struct DockGoal_
{
  typedef DockGoal_<ContainerAllocator> Type;

  DockGoal_()
    : dock(false)  {
    }
  DockGoal_(const ContainerAllocator& _alloc)
    : dock(false)  {
  (void)_alloc;
    }



   typedef uint8_t _dock_type;
  _dock_type dock;





  typedef boost::shared_ptr< ::caster_app::DockGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caster_app::DockGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DockGoal_

typedef ::caster_app::DockGoal_<std::allocator<void> > DockGoal;

typedef boost::shared_ptr< ::caster_app::DockGoal > DockGoalPtr;
typedef boost::shared_ptr< ::caster_app::DockGoal const> DockGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caster_app::DockGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caster_app::DockGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caster_app

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'caster_app': ['/home/caster/ros_ws/caster/devel/.private/caster_app/share/caster_app/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caster_app::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caster_app::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_app::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_app::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_app::DockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_app::DockGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caster_app::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "035360b0bb03f7f742a0b2d734a3a660";
  }

  static const char* value(const ::caster_app::DockGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x035360b0bb03f7f7ULL;
  static const uint64_t static_value2 = 0x42a0b2d734a3a660ULL;
};

template<class ContainerAllocator>
struct DataType< ::caster_app::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caster_app/DockGoal";
  }

  static const char* value(const ::caster_app::DockGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caster_app::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"bool dock\n"
;
  }

  static const char* value(const ::caster_app::DockGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caster_app::DockGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dock);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caster_app::DockGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caster_app::DockGoal_<ContainerAllocator>& v)
  {
    s << indent << "dock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dock);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASTER_APP_MESSAGE_DOCKGOAL_H
