// Generated by gencpp from file caster_app/DockResult.msg
// DO NOT EDIT!


#ifndef CASTER_APP_MESSAGE_DOCKRESULT_H
#define CASTER_APP_MESSAGE_DOCKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caster_app
{
template <class ContainerAllocator>
struct DockResult_
{
  typedef DockResult_<ContainerAllocator> Type;

  DockResult_()
    : dock_result()  {
    }
  DockResult_(const ContainerAllocator& _alloc)
    : dock_result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dock_result_type;
  _dock_result_type dock_result;





  typedef boost::shared_ptr< ::caster_app::DockResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caster_app::DockResult_<ContainerAllocator> const> ConstPtr;

}; // struct DockResult_

typedef ::caster_app::DockResult_<std::allocator<void> > DockResult;

typedef boost::shared_ptr< ::caster_app::DockResult > DockResultPtr;
typedef boost::shared_ptr< ::caster_app::DockResult const> DockResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caster_app::DockResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caster_app::DockResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caster_app

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'caster_app': ['/home/caster/ros_ws/caster/devel/.private/caster_app/share/caster_app/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caster_app::DockResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caster_app::DockResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_app::DockResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_app::DockResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_app::DockResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_app::DockResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caster_app::DockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00a5a8fbd4c58081cc52730ffbc30c99";
  }

  static const char* value(const ::caster_app::DockResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00a5a8fbd4c58081ULL;
  static const uint64_t static_value2 = 0xcc52730ffbc30c99ULL;
};

template<class ContainerAllocator>
struct DataType< ::caster_app::DockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caster_app/DockResult";
  }

  static const char* value(const ::caster_app::DockResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caster_app::DockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"string dock_result\n"
;
  }

  static const char* value(const ::caster_app::DockResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caster_app::DockResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dock_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caster_app::DockResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caster_app::DockResult_<ContainerAllocator>& v)
  {
    s << indent << "dock_result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dock_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASTER_APP_MESSAGE_DOCKRESULT_H
