; Auto-generated. Do not edit!


(cl:in-package caster_app-msg)


;//! \htmlinclude MovetoGoalGoal.msg.html

(cl:defclass <MovetoGoalGoal> (roslisp-msg-protocol:ros-message)
  ((goal_name
    :reader goal_name
    :initarg :goal_name
    :type cl:string
    :initform ""))
)

(cl:defclass MovetoGoalGoal (<MovetoGoalGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MovetoGoalGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MovetoGoalGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name caster_app-msg:<MovetoGoalGoal> is deprecated: use caster_app-msg:MovetoGoalGoal instead.")))

(cl:ensure-generic-function 'goal_name-val :lambda-list '(m))
(cl:defmethod goal_name-val ((m <MovetoGoalGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader caster_app-msg:goal_name-val is deprecated.  Use caster_app-msg:goal_name instead.")
  (goal_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MovetoGoalGoal>) ostream)
  "Serializes a message object of type '<MovetoGoalGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MovetoGoalGoal>) istream)
  "Deserializes a message object of type '<MovetoGoalGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MovetoGoalGoal>)))
  "Returns string type for a message object of type '<MovetoGoalGoal>"
  "caster_app/MovetoGoalGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MovetoGoalGoal)))
  "Returns string type for a message object of type 'MovetoGoalGoal"
  "caster_app/MovetoGoalGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MovetoGoalGoal>)))
  "Returns md5sum for a message object of type '<MovetoGoalGoal>"
  "254bb0d4018de3d871badc783fa8b12a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MovetoGoalGoal)))
  "Returns md5sum for a message object of type 'MovetoGoalGoal"
  "254bb0d4018de3d871badc783fa8b12a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MovetoGoalGoal>)))
  "Returns full string definition for message of type '<MovetoGoalGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string goal_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MovetoGoalGoal)))
  "Returns full string definition for message of type 'MovetoGoalGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string goal_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MovetoGoalGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MovetoGoalGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MovetoGoalGoal
    (cl:cons ':goal_name (goal_name msg))
))
