// Auto-generated. Do not edit!

// (in-package caster_app.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dock_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('dock_feedback')) {
        this.dock_feedback = initObj.dock_feedback
      }
      else {
        this.dock_feedback = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockFeedback
    // Serialize message field [dock_feedback]
    bufferOffset = _serializer.string(obj.dock_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockFeedback
    let len;
    let data = new DockFeedback(null);
    // Deserialize message field [dock_feedback]
    data.dock_feedback = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.dock_feedback.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'caster_app/DockFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b74bedcf617880cfc838cc9c2eaa7a17';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    string dock_feedback
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockFeedback(null);
    if (msg.dock_feedback !== undefined) {
      resolved.dock_feedback = msg.dock_feedback;
    }
    else {
      resolved.dock_feedback = ''
    }

    return resolved;
    }
};

module.exports = DockFeedback;
