// Auto-generated. Do not edit!

// (in-package caster_app.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dock_result = null;
    }
    else {
      if (initObj.hasOwnProperty('dock_result')) {
        this.dock_result = initObj.dock_result
      }
      else {
        this.dock_result = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockResult
    // Serialize message field [dock_result]
    bufferOffset = _serializer.string(obj.dock_result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockResult
    let len;
    let data = new DockResult(null);
    // Deserialize message field [dock_result]
    data.dock_result = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.dock_result.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'caster_app/DockResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '00a5a8fbd4c58081cc52730ffbc30c99';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    string dock_result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockResult(null);
    if (msg.dock_result !== undefined) {
      resolved.dock_result = msg.dock_result;
    }
    else {
      resolved.dock_result = ''
    }

    return resolved;
    }
};

module.exports = DockResult;
