// Generated by gencpp from file caster_base/SetDigitalOutput.msg
// DO NOT EDIT!


#ifndef CASTER_BASE_MESSAGE_SETDIGITALOUTPUT_H
#define CASTER_BASE_MESSAGE_SETDIGITALOUTPUT_H

#include <ros/service_traits.h>


#include <caster_base/SetDigitalOutputRequest.h>
#include <caster_base/SetDigitalOutputResponse.h>


namespace caster_base
{

struct SetDigitalOutput
{

typedef SetDigitalOutputRequest Request;
typedef SetDigitalOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDigitalOutput
} // namespace caster_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caster_base::SetDigitalOutput > {
  static const char* value()
  {
    return "8e8f7edb14600d5261e0451c1611a8b6";
  }

  static const char* value(const ::caster_base::SetDigitalOutput&) { return value(); }
};

template<>
struct DataType< ::caster_base::SetDigitalOutput > {
  static const char* value()
  {
    return "caster_base/SetDigitalOutput";
  }

  static const char* value(const ::caster_base::SetDigitalOutput&) { return value(); }
};


// service_traits::MD5Sum< ::caster_base::SetDigitalOutputRequest> should match 
// service_traits::MD5Sum< ::caster_base::SetDigitalOutput > 
template<>
struct MD5Sum< ::caster_base::SetDigitalOutputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caster_base::SetDigitalOutput >::value();
  }
  static const char* value(const ::caster_base::SetDigitalOutputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caster_base::SetDigitalOutputRequest> should match 
// service_traits::DataType< ::caster_base::SetDigitalOutput > 
template<>
struct DataType< ::caster_base::SetDigitalOutputRequest>
{
  static const char* value()
  {
    return DataType< ::caster_base::SetDigitalOutput >::value();
  }
  static const char* value(const ::caster_base::SetDigitalOutputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caster_base::SetDigitalOutputResponse> should match 
// service_traits::MD5Sum< ::caster_base::SetDigitalOutput > 
template<>
struct MD5Sum< ::caster_base::SetDigitalOutputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caster_base::SetDigitalOutput >::value();
  }
  static const char* value(const ::caster_base::SetDigitalOutputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caster_base::SetDigitalOutputResponse> should match 
// service_traits::DataType< ::caster_base::SetDigitalOutput > 
template<>
struct DataType< ::caster_base::SetDigitalOutputResponse>
{
  static const char* value()
  {
    return DataType< ::caster_base::SetDigitalOutput >::value();
  }
  static const char* value(const ::caster_base::SetDigitalOutputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CASTER_BASE_MESSAGE_SETDIGITALOUTPUT_H
