// Generated by gencpp from file caster_base/SetDigitalOutputResponse.msg
// DO NOT EDIT!


#ifndef CASTER_BASE_MESSAGE_SETDIGITALOUTPUTRESPONSE_H
#define CASTER_BASE_MESSAGE_SETDIGITALOUTPUTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caster_base
{
template <class ContainerAllocator>
struct SetDigitalOutputResponse_
{
  typedef SetDigitalOutputResponse_<ContainerAllocator> Type;

  SetDigitalOutputResponse_()
    : result(false)  {
    }
  SetDigitalOutputResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetDigitalOutputResponse_

typedef ::caster_base::SetDigitalOutputResponse_<std::allocator<void> > SetDigitalOutputResponse;

typedef boost::shared_ptr< ::caster_base::SetDigitalOutputResponse > SetDigitalOutputResponsePtr;
typedef boost::shared_ptr< ::caster_base::SetDigitalOutputResponse const> SetDigitalOutputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caster_base

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::caster_base::SetDigitalOutputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caster_base/SetDigitalOutputResponse";
  }

  static const char* value(const ::caster_base::SetDigitalOutputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::caster_base::SetDigitalOutputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDigitalOutputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caster_base::SetDigitalOutputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caster_base::SetDigitalOutputResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASTER_BASE_MESSAGE_SETDIGITALOUTPUTRESPONSE_H
