; Auto-generated. Do not edit!


(cl:in-package caster_app-msg)


;//! \htmlinclude MovetoGoalFeedback.msg.html

(cl:defclass <MovetoGoalFeedback> (roslisp-msg-protocol:ros-message)
  ((moveto_feedback
    :reader moveto_feedback
    :initarg :moveto_feedback
    :type cl:string
    :initform ""))
)

(cl:defclass MovetoGoalFeedback (<MovetoGoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MovetoGoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MovetoGoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name caster_app-msg:<MovetoGoalFeedback> is deprecated: use caster_app-msg:MovetoGoalFeedback instead.")))

(cl:ensure-generic-function 'moveto_feedback-val :lambda-list '(m))
(cl:defmethod moveto_feedback-val ((m <MovetoGoalFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader caster_app-msg:moveto_feedback-val is deprecated.  Use caster_app-msg:moveto_feedback instead.")
  (moveto_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MovetoGoalFeedback>) ostream)
  "Serializes a message object of type '<MovetoGoalFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'moveto_feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'moveto_feedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MovetoGoalFeedback>) istream)
  "Deserializes a message object of type '<MovetoGoalFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'moveto_feedback) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'moveto_feedback) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MovetoGoalFeedback>)))
  "Returns string type for a message object of type '<MovetoGoalFeedback>"
  "caster_app/MovetoGoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MovetoGoalFeedback)))
  "Returns string type for a message object of type 'MovetoGoalFeedback"
  "caster_app/MovetoGoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MovetoGoalFeedback>)))
  "Returns md5sum for a message object of type '<MovetoGoalFeedback>"
  "9947d2ec7b946da85f364ab72add6975")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MovetoGoalFeedback)))
  "Returns md5sum for a message object of type 'MovetoGoalFeedback"
  "9947d2ec7b946da85f364ab72add6975")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MovetoGoalFeedback>)))
  "Returns full string definition for message of type '<MovetoGoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%string moveto_feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MovetoGoalFeedback)))
  "Returns full string definition for message of type 'MovetoGoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%string moveto_feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MovetoGoalFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'moveto_feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MovetoGoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MovetoGoalFeedback
    (cl:cons ':moveto_feedback (moveto_feedback msg))
))
