; Auto-generated. Do not edit!


(cl:in-package caster_app-msg)


;//! \htmlinclude MovetoGoalResult.msg.html

(cl:defclass <MovetoGoalResult> (roslisp-msg-protocol:ros-message)
  ((moveto_result
    :reader moveto_result
    :initarg :moveto_result
    :type cl:string
    :initform ""))
)

(cl:defclass MovetoGoalResult (<MovetoGoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MovetoGoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MovetoGoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name caster_app-msg:<MovetoGoalResult> is deprecated: use caster_app-msg:MovetoGoalResult instead.")))

(cl:ensure-generic-function 'moveto_result-val :lambda-list '(m))
(cl:defmethod moveto_result-val ((m <MovetoGoalResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader caster_app-msg:moveto_result-val is deprecated.  Use caster_app-msg:moveto_result instead.")
  (moveto_result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MovetoGoalResult>) ostream)
  "Serializes a message object of type '<MovetoGoalResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'moveto_result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'moveto_result))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MovetoGoalResult>) istream)
  "Deserializes a message object of type '<MovetoGoalResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'moveto_result) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'moveto_result) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MovetoGoalResult>)))
  "Returns string type for a message object of type '<MovetoGoalResult>"
  "caster_app/MovetoGoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MovetoGoalResult)))
  "Returns string type for a message object of type 'MovetoGoalResult"
  "caster_app/MovetoGoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MovetoGoalResult>)))
  "Returns md5sum for a message object of type '<MovetoGoalResult>"
  "3fbfca23b1bcd8fe0f6eed5542cd54f9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MovetoGoalResult)))
  "Returns md5sum for a message object of type 'MovetoGoalResult"
  "3fbfca23b1bcd8fe0f6eed5542cd54f9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MovetoGoalResult>)))
  "Returns full string definition for message of type '<MovetoGoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%string moveto_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MovetoGoalResult)))
  "Returns full string definition for message of type 'MovetoGoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%string moveto_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MovetoGoalResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'moveto_result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MovetoGoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MovetoGoalResult
    (cl:cons ':moveto_result (moveto_result msg))
))
