// Generated by gencpp from file caster_man_app/PickGiftResponse.msg
// DO NOT EDIT!


#ifndef CASTER_MAN_APP_MESSAGE_PICKGIFTRESPONSE_H
#define CASTER_MAN_APP_MESSAGE_PICKGIFTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caster_man_app
{
template <class ContainerAllocator>
struct PickGiftResponse_
{
  typedef PickGiftResponse_<ContainerAllocator> Type;

  PickGiftResponse_()
    : result(0)  {
    }
  PickGiftResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::caster_man_app::PickGiftResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caster_man_app::PickGiftResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PickGiftResponse_

typedef ::caster_man_app::PickGiftResponse_<std::allocator<void> > PickGiftResponse;

typedef boost::shared_ptr< ::caster_man_app::PickGiftResponse > PickGiftResponsePtr;
typedef boost::shared_ptr< ::caster_man_app::PickGiftResponse const> PickGiftResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caster_man_app::PickGiftResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caster_man_app

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caster_man_app::PickGiftResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_man_app::PickGiftResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_man_app::PickGiftResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::caster_man_app::PickGiftResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caster_man_app/PickGiftResponse";
  }

  static const char* value(const ::caster_man_app::PickGiftResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result\n"
;
  }

  static const char* value(const ::caster_man_app::PickGiftResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickGiftResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caster_man_app::PickGiftResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caster_man_app::PickGiftResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASTER_MAN_APP_MESSAGE_PICKGIFTRESPONSE_H
