(cl:in-package hongfu_bms_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          RESIDUALCAPACITY-VAL
          RESIDUALCAPACITY
          DESIGNCAPACITY-VAL
          DESIGNCAPACITY
          CYCLEINDEX-VAL
          CYCLEINDEX
          DATAPRODUCTION-VAL
          DATAPRODUCTION
          STATUSBALANCE-VAL
          STATUSBALANCE
          STATUSPROTECT-VAL
          STATUSPROTECT
          VERSION-VAL
          VERSION
          RSOC-VAL
          RSOC
          STATUEMOS-VAL
          STATUEMOS
          CELLNUMBER-VAL
          CELLNUMBER
          NTCNUMBER-VAL
          NTCNUMBER
          NTCTEM-VAL
          NTCTEM
          CELLVOLTAGE-VAL
          CELLVOLTAGE
          ERRORID-VAL
          ERRORID
          ERRORINFO-VAL
          ERRORINFO
))