// Generated by gencpp from file caster_man_app/PickGift.msg
// DO NOT EDIT!


#ifndef CASTER_MAN_APP_MESSAGE_PICKGIFT_H
#define CASTER_MAN_APP_MESSAGE_PICKGIFT_H

#include <ros/service_traits.h>


#include <caster_man_app/PickGiftRequest.h>
#include <caster_man_app/PickGiftResponse.h>


namespace caster_man_app
{

struct PickGift
{

typedef PickGiftRequest Request;
typedef PickGiftResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickGift
} // namespace caster_man_app


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caster_man_app::PickGift > {
  static const char* value()
  {
    return "b42d9d996fb6059732e031bfe10aef07";
  }

  static const char* value(const ::caster_man_app::PickGift&) { return value(); }
};

template<>
struct DataType< ::caster_man_app::PickGift > {
  static const char* value()
  {
    return "caster_man_app/PickGift";
  }

  static const char* value(const ::caster_man_app::PickGift&) { return value(); }
};


// service_traits::MD5Sum< ::caster_man_app::PickGiftRequest> should match 
// service_traits::MD5Sum< ::caster_man_app::PickGift > 
template<>
struct MD5Sum< ::caster_man_app::PickGiftRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caster_man_app::PickGift >::value();
  }
  static const char* value(const ::caster_man_app::PickGiftRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caster_man_app::PickGiftRequest> should match 
// service_traits::DataType< ::caster_man_app::PickGift > 
template<>
struct DataType< ::caster_man_app::PickGiftRequest>
{
  static const char* value()
  {
    return DataType< ::caster_man_app::PickGift >::value();
  }
  static const char* value(const ::caster_man_app::PickGiftRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caster_man_app::PickGiftResponse> should match 
// service_traits::MD5Sum< ::caster_man_app::PickGift > 
template<>
struct MD5Sum< ::caster_man_app::PickGiftResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caster_man_app::PickGift >::value();
  }
  static const char* value(const ::caster_man_app::PickGiftResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caster_man_app::PickGiftResponse> should match 
// service_traits::DataType< ::caster_man_app::PickGift > 
template<>
struct DataType< ::caster_man_app::PickGiftResponse>
{
  static const char* value()
  {
    return DataType< ::caster_man_app::PickGift >::value();
  }
  static const char* value(const ::caster_man_app::PickGiftResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CASTER_MAN_APP_MESSAGE_PICKGIFT_H
