// Generated by gencpp from file caster_man_app/PickGiftRequest.msg
// DO NOT EDIT!


#ifndef CASTER_MAN_APP_MESSAGE_PICKGIFTREQUEST_H
#define CASTER_MAN_APP_MESSAGE_PICKGIFTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caster_man_app
{
template <class ContainerAllocator>
struct PickGiftRequest_
{
  typedef PickGiftRequest_<ContainerAllocator> Type;

  PickGiftRequest_()
    : id()  {
    }
  PickGiftRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::caster_man_app::PickGiftRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caster_man_app::PickGiftRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PickGiftRequest_

typedef ::caster_man_app::PickGiftRequest_<std::allocator<void> > PickGiftRequest;

typedef boost::shared_ptr< ::caster_man_app::PickGiftRequest > PickGiftRequestPtr;
typedef boost::shared_ptr< ::caster_man_app::PickGiftRequest const> PickGiftRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caster_man_app::PickGiftRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caster_man_app

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caster_man_app::PickGiftRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_man_app::PickGiftRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_man_app::PickGiftRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const ::caster_man_app::PickGiftRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbfcda76036ebbe3ULL;
  static const uint64_t static_value2 = 0xd36caf7af80b260cULL;
};

template<class ContainerAllocator>
struct DataType< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caster_man_app/PickGiftRequest";
  }

  static const char* value(const ::caster_man_app::PickGiftRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
;
  }

  static const char* value(const ::caster_man_app::PickGiftRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickGiftRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caster_man_app::PickGiftRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caster_man_app::PickGiftRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASTER_MAN_APP_MESSAGE_PICKGIFTREQUEST_H
