// Generated by gencpp from file caster_base/SetDigitalOutputRequest.msg
// DO NOT EDIT!


#ifndef CASTER_BASE_MESSAGE_SETDIGITALOUTPUTREQUEST_H
#define CASTER_BASE_MESSAGE_SETDIGITALOUTPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caster_base
{
template <class ContainerAllocator>
struct SetDigitalOutputRequest_
{
  typedef SetDigitalOutputRequest_<ContainerAllocator> Type;

  SetDigitalOutputRequest_()
    : io(0)
    , active(false)  {
    }
  SetDigitalOutputRequest_(const ContainerAllocator& _alloc)
    : io(0)
    , active(false)  {
  (void)_alloc;
    }



   typedef uint8_t _io_type;
  _io_type io;

   typedef uint8_t _active_type;
  _active_type active;





  typedef boost::shared_ptr< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDigitalOutputRequest_

typedef ::caster_base::SetDigitalOutputRequest_<std::allocator<void> > SetDigitalOutputRequest;

typedef boost::shared_ptr< ::caster_base::SetDigitalOutputRequest > SetDigitalOutputRequestPtr;
typedef boost::shared_ptr< ::caster_base::SetDigitalOutputRequest const> SetDigitalOutputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caster_base

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8756db3fdda890ff1a693494ca12fd1";
  }

  static const char* value(const ::caster_base::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8756db3fdda890fULL;
  static const uint64_t static_value2 = 0xf1a693494ca12fd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caster_base/SetDigitalOutputRequest";
  }

  static const char* value(const ::caster_base::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 io\n"
"bool active\n"
;
  }

  static const char* value(const ::caster_base::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.io);
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDigitalOutputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caster_base::SetDigitalOutputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caster_base::SetDigitalOutputRequest_<ContainerAllocator>& v)
  {
    s << indent << "io: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io);
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASTER_BASE_MESSAGE_SETDIGITALOUTPUTREQUEST_H
